### ISSUE TITLE
Make Each Steps Undoable (& Redoable)

### ISSUE THREAD

**Issue by hieroglyphic** [djfun/mc-map-item-tool#11]
When a user accidentally select wrong button or change his/her mind during the process, it is often inconvinient to do it all over again.

**Comment by djfun** [comment]
added in 1252fef5a3c47ddc501de224a9815ef62725d8d5 and e9ab0bc7696435a9895d088355d31e508e062633

**Comment by hieroglyphic** [comment]
​Too awesome for me​!

gothic by google
