### ISSUE TITLE
Add transparency threshold support

### ISSUE THREAD

**Issue by hieroglyphic** [djfun/mc-map-item-tool#12]
Got an idea from https://github.com/djfun/mc-map-item-tool/issues/1

**Comment by djfun** [comment]
So you want to control how transparent a pixel in the original has to be, that it is mapped to a transparent pixel in the minecraft map?
Did I understand that correctly? That would be pretty easy to implement.

**Comment by hieroglyphic** [comment]
Yes.

**Comment by djfun** [comment]
fixed in 804696458caf87c08afe465309fd34795709f4da
