### ISSUE TITLE
Retrieving raw images instead of map files

### ISSUE THREAD

**Issue by heyitsdoodler** [djfun/mc-map-item-tool#21]

**Comment by NurdTurd** [comment]
@MinecraftDoodler could you explain your setup? I'm interested.

**Comment by MinecraftDoodler** [comment]
what i want is something that can split the image up into .pngs the size of maps so i can load them on to my server With my PngMap.jar plugin

**Comment by MinecraftDoodler** [comment]
so pngs instead .dat files

**Comment by MinecraftDoodler** [comment]
:)
