### ISSUE TITLE
部分替换不起作用

### ISSUE THREAD

**Issue by Wdam** [djfun/mc-map-item-tool#60]
游戏版本：1.16.1
服务器：spigot
图片：
![06](https://user-images.githubusercontent.com/42366809/105131586-2e612200-5b24-11eb-870c-7c7617066b94.jpg)

**Comment by djfun** [comment]
Hi, I can't read Chinese. Can you explain your issue in detail in English? ie. steps to reproduce, expected result and actual result

**Comment by GalaxyLinus** [comment]
Game version: 1.16.1
 Server: spigot
 image:

**Comment by Wdam** [comment]
> Hi, I can't read Chinese. Can you explain your issue in detail in English? ie. steps to reproduce, expected result and actual result

The website can only replace some of the map files, and the others have not changed. I tried many times without success. My game version is 1.16.1, I am a server administrator, the translation comes from Google
