### ISSUE TITLE
Horizontal & Vertical limits.

### ISSUE THREAD

**Issue by amirshah2935** [djfun/mc-map-item-tool#64]
![image](https://user-images.githubusercontent.com/38003845/118820871-3fab1700-b8e9-11eb-9245-0483f1164810.png)

im not usre why i cannot choose more Vertical and Horizontal..its jsut limit me to 4 x 1

**Comment by djfun** [comment]
Most likely your image is too small. If you increase the width and height of your original image, mc-map-item-tool will offer more options for "horizontal" and "vertical".

**Comment by amirshah2935** [comment]
yup thanks tested it..sorry for the trouble
