### ISSUE TITLE
New Feature for creating more parts of map Request

### ISSUE THREAD

**Issue by creamIcec** [djfun/mc-map-item-tool#69]
Thank you for providing us such an excellent map tool!
But your tool can only create 6 parts in horizon and 9 in vertical,
can you expand the size of both of them?
Maybe there will be larger maps.

**Comment by djfun** [comment]
hi @creamIcec 
The number of horizontal and vertical parts depends on the resolution of the input image. If your input image has a larger size, you should be able to split into more parts.

**Comment by creamIcec** [comment]
thank you.
but what if i want more parts of map without changing the size of image?

**Comment by creamIcec** [comment]
Thanks for your help!
