### ISSUE TITLE
Notify users when the server has finished creating the files

### ISSUE THREAD

**Issue by djfun** [djfun/mc-map-item-tool#8]
As users sometimes have to wait quite a while for the server to finish, they should have a way of getting notified.
Easiest way to do that would be via email, other methods need to be investigated.

**Comment by hieroglyphic** [comment]
Maybe implement [Notification](https://developer.mozilla.org/en/docs/Web/API/notification)?

**Comment by djfun** [comment]
sounds like a good idea, I'll look into it

**Comment by djfun** [comment]
I implemented the web notifications feature.
Before the last step you can check a checkbox, the browser will ask for permissions and when the processing is finished the notification will be displayed.
If the browser doesn't support web notifications, there is no checkbox.
As these notifications are still experimental technology, there does not seem to be a way to stop them from automatically closing after a few seconds (at least in Firefox).

**Comment by hieroglyphic** [comment]
How about using alert() when Notification is not supported?
