### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by Anonymous421391** [djfun/mc-map-item-tool#82]
Hi.

The website https://mc-map.djfun.de/ is down, error 502 Bad Gateway. Will it be brought back online? If not, could you please make an offline version of this tool, perhaps one compiled into an executable file? Thank you so much. May God bless. Jesus Christ loves you! You are precious and irreplaceable and you matter! Take care. :)

**Comment by djfun** [comment]
Thanks for the report. I'll look into the problem

**Comment by djfun** [comment]
It seems like there was a problem with the latest nodejs update on the server. I updated everything to support node 18 in 02016a896acb34945d2341b28d3d6cb04b82eebf and restarted the application.

**Comment by Anonymous421391** [comment]
Thank you so, so much! I love your Minecraft map tool and use it a ton. You
do great work and I really appreciate it. Thanks for fixing the issue! Have
a great day. :)
